<?php

define("CORONAID_TABLE",'CORONAID_TABLE');
define("CORONA_CONTACTS_TABLE",'CORONA_CONTACTS_TABLE');
define("CORONA_AST_TABLE",'CORONA_AST_TABLE');
define("BOOTSTRAP_CSS",'BOOTSTRAP_CSS');
define("BOOTSTRAP_JS",'BOOTSTRAP_JS');
define("JSPDF_POLY_JS",'JSPDF_POLY_JS');
define("JSPDF_JS",'JSPDF_JS');
define("JSPDF_AUTOTABLE_JS",'JSPDF_AUTOTABLE_JS');
define("SECURIMAGE_PHP",'SECURIMAGE_PHP');
define("SECURIMAGE_BASE",'SECURIMAGE_BASE');
define("SECURIMAGE_JS",'SECURIMAGE_JS');
define("SECURIMAGE_CSS",'SECURIMAGE_CSS');
define("SECURIMAGE_AJAX",'SECURIMAGE_AJAX');


?>